frame_id: odom
# initial_orientation: [0, 0, 0, 1]
# initial_x: 0
# initial_y: 0
# initial_z: 0
object_a: 0.2
object_b: 0.2
object_g: 0.0
object_r: 0.0
object_type: cube
object_x: 0.865
object_y: 0.865
object_z: 1.0
publish_tf: true
tf_duration: 0.05
tf_frame: kiva_pod_base
